### ISSUE TITLE
2 m / 1 m = 2 ✔️,  2 m / 100 cm = 0.02 m.cm-1 ❌ 

### ISSUE THREAD

**Issue by danny-boy-online** [Invenietis/CK-UnitsOfMeasure#3]
I think there is an issue with dividing quantities with different prefixes as illustrated below.
In the real world both results should be equal.

```
static void Main(string[] args)
{
    var metre = MeasureUnit.Metre;
    var a = 2.WithUnit(metre);
    var b = 1.WithUnit(metre);
    var centimetre = MeasureStandardPrefix.Centi[metre];
    var c = 100.WithUnit(centimetre);
    var div1 = a / b;
    var div2 = a / c;
    Console.WriteLine($"div1={div1}");
    Console.WriteLine($"div2={div2}");
    Console.WriteLine($"div1 == div2 :{div1 == div2}");
    Console.WriteLine($"div1.Equals(div2):{div1.Equals(div2)}");
    var mult1 = a * b;
    var mult2 = a * c;
    Console.WriteLine($"mult1={mult1}");
    Console.WriteLine($"mult2={mult2}");
    Console.WriteLine($"mult1 == mult2 :{mult1 == mult2}");
    Console.WriteLine($"mult1.Equals(mult2):{mult1.Equals(mult2)}");
}
```

Console output:

div1=2                         :heavy_check_mark: 
div2=0.02 _m.cm-1_       :x:  incorrect
div1 == div2 :False         :x: comparison now fails to reflect reality
div1.Equals(div2):False    :x: 

mult1=2 m2               :heavy_check_mark:
mult2=200 _cm.m_         :x:  incorrect
mult1 == mult2 :True  :heavy_check_mark:
mult1.Equals(mult2):True  :heavy_check_mark:

**Comment by olivier-spinelli** [comment]
This is a question answered in the update of the article:

2020-02-11
- Concerning the implicit conversion/simplification asked by Dave Hary in its first question, this would oblige to implicitly choose a simplified unit but this impacts the multiplication factor. 
For example: multiplying "5 kg" by "7 g" gives us "35 g.kg" (units are ordered by descending power and then by lexicographic order). These 2 units share the same normalized unit (the kg): one may simplify them by kg²... However this has an obvious impact on the value itself as the following test shows it.
```csharp
[Test]
public void automatic_unit_simplification_impacts_the_value()
{
  var q = 5.WithUnit( MeasureUnit.Kilogram ) * 7.WithUnit( MeasureUnit.Gram );
  q.ToString().Should().Be( "35 g.kg" );

  q.Unit.Normalization.Should().Be( MeasureUnit.Kilogram * MeasureUnit.Kilogram );
  q.Unit.NormalizationFactor.Should().Be( new ExpFactor( 0, -3 ) );

  var qkg = q.ConvertTo( MeasureUnit.Kilogram * MeasureUnit.Kilogram );
  qkg.Value.Should().Be( 35.0 / 1000 );

  var qg = q.ConvertTo( MeasureUnit.Gram * MeasureUnit.Gram );
  qg.Value.Should().Be( 35.0 * 1000 );
}
``` 

**Question:** Should the value be 0.035 (in kg²) or 35000 (in g²)?

**Answer:** We consider that we should not decide this: it is up to the user/developer to decide to use the "normalized" unit (that is always available) or any variation of it through conversion.

**Comment by danny-boy-online** [comment]
Hi Olivier, i do recall reading that note in your article but i guess i didn't understand why you'd not made the Equals(qKg2, qKg_g) method compare the Normalizations ?  Is it something you'd considered and rejected?

I can see how the User/developer can make a conscious decision to normalize units as they go.  However in my scenario runtime client code can encounter quantities supplied from distinct server requests that the client code knows nothing about other than that it should compare them - and take action according to whether they are identical.  So for my use case I need to write my own wrapper method to override Equals() so that it compares their normalized values.

**Comment by olivier-spinelli** [comment]
I'm a bit surprised. I added a final statement to the previous test that shows that the Equals actually uses the normalization. 
```csharp
        [Test]
        public void automatic_unit_simplification_impacts_the_value()
        {
            var q = 5.WithUnit( MeasureUnit.Kilogram ) * 7.WithUnit( MeasureUnit.Gram );
            q.ToString().Should().Be( "35 g.kg" );

            q.Unit.Normalization.Should().Be( MeasureUnit.Kilogram * MeasureUnit.Kilogram );
            q.Unit.NormalizationFactor.Should().Be( new ExpFactor( 0, -3 ) );

            var qkg = q.ConvertTo( MeasureUnit.Kilogram * MeasureUnit.Kilogram );
            qkg.Value.Should().Be( 35.0 / 1000 );
            
            var qg = q.ConvertTo( MeasureUnit.Gram * MeasureUnit.Gram );
            qg.Value.Should().Be( 35.0 * 1000 );

            qkg.Equals( qg ).Should().BeTrue();
        }
```

This is how it's implemented:
```csharp
        /// <summary>
        /// Overridden to support Unit aware equality. See <see cref="Equals(Quantity)"/>.
        /// </summary>
        /// <param name="obj">The object to test.</param>
        /// <returns>True if this quantity is the same as the one, false otherwise.</returns>
        public override bool Equals( object obj ) => obj is Quantity q && Equals( q );

        /// <summary>
        /// Overridden to support Unit aware equality.
        /// </summary>
        /// <returns>The hash code to use for this quantity.</returns>
        public override int GetHashCode() => Unit.Normalization.GetHashCode() ^ ToNormalizedString().GetHashCode();

        /// <summary>
        /// Checks if this quantity is equal to another one: its <see cref="ToNormalizedString"/>
        /// is the same as the other quantity (and they belong to the same <see cref="MeasureContext"/>).
        /// </summary>
        /// <param name="other">The quantity that may be equal to this.</param>
        /// <returns>True if this quantity is the same as the other one, false otherwise.</returns>
        public bool Equals( Quantity other ) => Unit.Context == other.Unit.Context
                                                && ToNormalizedString() == other.ToNormalizedString();
```
It does use the Normalized form...

**Comment by danny-boy-online** [comment]
In answer to the question you ask:
Question: Should the value be 0.035 (in kg²) or 35000 (in g²)?

The answer in my case is that either is preferable to getting kg.g of g.kg as a result.
To achieve this I have take your normalization checks in your Quantity.CompareTo() method and added them to the Quantity.Multiply(Quantity other), so that the result will always be in the units of the quantity on the LHS of the multiplication.  This yields consistent predictable behaviour, valid units, correct follow-on Equality and Comparison , and power as a developer to choose which quantity i put on the LHS or RHS of the multiplication so that I can control the outcome.
I haven't thoroughly tested this yet though.

code:
```
        public Quantity Multiply(Quantity q)
        {
            // get the units and values
            var tU = this.Unit;
            var oU = q.Unit;
            var tV = this.Value;
            var oV = q.Value;

            // Same normalized units, we convert the other unit before multiplication.
            if (tU.Normalization == oU.Normalization)
            {
                FullFactor ratio = oU.NormalizationFactor.DivideBy(tU.NormalizationFactor);
                oV = (oV * ratio.ToDouble());
                oU = tU;
            }
            // Inverted normalized units, we convert the other unit before multiplication.
            else if (tU.Normalization == oU.Normalization.Invert())
            {
                FullFactor ratio = oU.NormalizationFactor.Multiply(tU.NormalizationFactor);
                oV = (1 / (oV * ratio.ToDouble()));
                oU = tU.Invert();
            }

            return new Quantity(tV * oV, tU * oU);
        }

```

**Comment by olivier-spinelli** [comment]
Privilegiating the LHS is a good choice. I think that this should remain a convention (that has to be uniformally adopted globally by an implementation).

**Comment by danny-boy-online** [comment]
Fair enough.
However, the _currently published_ Equals() implementation for the case I posted here ... 

result1 = 2m / 1 m 
result2 = 2m / 100 cm
result1.Equals(result2)  // yields FALSE

does not yield true.  
I think that is still an issue.  Perhaps a separate one?

**Comment by olivier-spinelli** [comment]
Yes it is the Non-Unit (the "None") case. r1 is bound to the null context (no unit by design) and r2 to the original context since its unit ultimately resolves to the None but is "m.cm-1".
I've just pushed a fix to the Equals and CompareTo methods to correctly handle this "None" case!
Thank you ;)
